/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author Ha Chi
 */
public class ThoiKhoaBieu extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThoiKhoaBieu
     */
    public ThoiKhoaBieu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThoiKhoaBieu = new javax.swing.JPanel();
        btnThoiKhoaBieu = new javax.swing.JButton();
        spThoiKhoaBieu = new javax.swing.JScrollPane();
        tblThoiKhoaBieu = new javax.swing.JTable();
        cbxMonHoc = new javax.swing.JComboBox<>();

        pnThoiKhoaBieu.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời khóa biểu"));

        btnThoiKhoaBieu.setText("Import thời khóa biểu");
        btnThoiKhoaBieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiKhoaBieuActionPerformed(evt);
            }
        });

        tblThoiKhoaBieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spThoiKhoaBieu.setViewportView(tblThoiKhoaBieu);

        cbxMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMonHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThoiKhoaBieuLayout = new javax.swing.GroupLayout(pnThoiKhoaBieu);
        pnThoiKhoaBieu.setLayout(pnThoiKhoaBieuLayout);
        pnThoiKhoaBieuLayout.setHorizontalGroup(
            pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThoiKhoaBieuLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(cbxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnThoiKhoaBieu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThoiKhoaBieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spThoiKhoaBieu)
                .addContainerGap())
        );
        pnThoiKhoaBieuLayout.setVerticalGroup(
            pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThoiKhoaBieuLayout.createSequentialGroup()
                .addGroup(pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxMonHoc)
                    .addComponent(btnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(spThoiKhoaBieu, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoiKhoaBieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiKhoaBieuActionPerformed

    }//GEN-LAST:event_btnThoiKhoaBieuActionPerformed

    private void cbxMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMonHocActionPerformed

    }//GEN-LAST:event_cbxMonHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoiKhoaBieu;
    private javax.swing.JComboBox<String> cbxMonHoc;
    private javax.swing.JPanel pnThoiKhoaBieu;
    private javax.swing.JScrollPane spThoiKhoaBieu;
    private javax.swing.JTable tblThoiKhoaBieu;
    // End of variables declaration//GEN-END:variables
}
