/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import static form.SinhVien.filename;
import helper.FileHandler;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.SinhVienObj;
import model.ThoiKhoaBieuObj;

/**
 *
 * @author Ha Chi
 */
public class ThoiKhoaBieu extends javax.swing.JInternalFrame {

    private final JFileChooser filesThoiKhoaBieu;
    private String folder, filename;

    /**
     * Creates new form ThoiKhoaBieu
     * @throws java.io.IOException
     */
    public ThoiKhoaBieu() throws IOException {
        initComponents();
        filesThoiKhoaBieu = new JFileChooser();
        filesThoiKhoaBieu.setCurrentDirectory(new File("C:\\Users\\Ha Chi\\Desktop"));
        filesThoiKhoaBieu.setFileFilter(new FileNameExtensionFilter("File CSV", "csv"));
        LoadlistThoiKhoaBieu();
        LoadThoiKhoaBieu(filename);
    }

    public void LoadlistThoiKhoaBieu() {
        try {
            File f = new File("src/resource/ThoiKhoaBieut");
            String[] files = f.list();
            for (String file : files) {
                cbxMonHoc.addItem(filename(file, '/', '.'));
            }
        } catch (Exception ex) {
            ex.getMessage();
        }
    }

    private void LoadThoiKhoaBieu(String filename) throws IOException {
        List<ThoiKhoaBieuObj> lst = new ArrayList<>();
        List<String> list = FileHandler.readAllLine(filename);
        if (!list.isEmpty()) {
            int size = list.size();
            for (int i = 0; i < size; i++) {
                String[] str = list.get(i).split(",");
                ThoiKhoaBieuObj tkb = new ThoiKhoaBieuObj(str[0], str[1], str[2]);
                lst.add(tkb);
            }
            DefaultTableModel model = (DefaultTableModel) tblThoiKhoaBieu.getModel();
            model.setRowCount(0);
            String[] columnsName = {"STT", "Mã môn", "Tên môn", "Phòng học"};
            model.setColumnIdentifiers(columnsName);
            int i = 1;
            for (ThoiKhoaBieuObj st : lst) {
                Vector row = new Vector();
                String number = Integer.toString(i);
                row.add(number);
                row.add(st.getMaMon());
                row.add(st.getTenMon());
                row.add(st.getPhongHoc());
                model.addRow(row);
                i++;
            }
            tblThoiKhoaBieu.setModel(model);
        }
    }

    public static String filename(String str, char sep, char ext) {
        String fullpath = str;
        int dot1 = fullpath.lastIndexOf(ext);
        int sep1 = fullpath.lastIndexOf(sep);
        return fullpath.substring(sep1 + 1, dot1);
    }

    public String convertObjectToString(List<SinhVienObj> lstnew) {
        String str = "";
        for (SinhVienObj sv : lstnew) {
            if (sv != null) {
                str += sv.convertObjectToString(sv) + "\n";
            }
        }
        return str;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThoiKhoaBieu = new javax.swing.JPanel();
        btnThoiKhoaBieu = new javax.swing.JButton();
        spThoiKhoaBieu = new javax.swing.JScrollPane();
        tblThoiKhoaBieu = new javax.swing.JTable();
        cbxMonHoc = new javax.swing.JComboBox<>();

        pnThoiKhoaBieu.setBorder(javax.swing.BorderFactory.createTitledBorder("Thời khóa biểu"));

        btnThoiKhoaBieu.setText("Import thời khóa biểu");
        btnThoiKhoaBieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoiKhoaBieuActionPerformed(evt);
            }
        });

        tblThoiKhoaBieu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        spThoiKhoaBieu.setViewportView(tblThoiKhoaBieu);

        cbxMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMonHocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThoiKhoaBieuLayout = new javax.swing.GroupLayout(pnThoiKhoaBieu);
        pnThoiKhoaBieu.setLayout(pnThoiKhoaBieuLayout);
        pnThoiKhoaBieuLayout.setHorizontalGroup(
            pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThoiKhoaBieuLayout.createSequentialGroup()
                .addContainerGap(219, Short.MAX_VALUE)
                .addComponent(cbxMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnThoiKhoaBieu, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(290, 290, 290))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThoiKhoaBieuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(spThoiKhoaBieu)
                .addContainerGap())
        );
        pnThoiKhoaBieuLayout.setVerticalGroup(
            pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThoiKhoaBieuLayout.createSequentialGroup()
                .addGroup(pnThoiKhoaBieuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbxMonHoc)
                    .addComponent(btnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(spThoiKhoaBieu, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(pnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnThoiKhoaBieu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThoiKhoaBieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoiKhoaBieuActionPerformed
        int returnvalue = filesThoiKhoaBieu.showOpenDialog(this);
        String dir = "src/resource/ThoiKhoaBieu";
        if (returnvalue == JFileChooser.APPROVE_OPTION) {
            File file = filesThoiKhoaBieu.getSelectedFile();
            try {
                filename = file.toString();
                String files = filename(filename, '\\', '.');
                File f = new File(dir, files + ".csv");
                if (f.exists()) {
                    JOptionPane.showMessageDialog(this, "File này đã có, nếu bạn muốn thêm sinh viên vào lớp thì thêm vào phần bên trái");
                } else {
                    List<String> lstimportdanhsach = FileHandler.readAllLineFileImport(filename);
                    int size = lstimportdanhsach.size();
                    for (int i = 0; i < size; i++) {
                        FileHandler.writeToFile(lstimportdanhsach.get(i), files + ".csv", true);
                    }
                    cbxMonHoc.removeAllItems();
                    LoadlistThoiKhoaBieu();
                    LoadThoiKhoaBieu(files + ".csv");
                }
            } catch (Exception ex) {
                ex.getMessage();
            }
        }
    }//GEN-LAST:event_btnThoiKhoaBieuActionPerformed

    private void cbxMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMonHocActionPerformed
        filename = cbxMonHoc.getSelectedItem() + ".csv";
        try {
            LoadThoiKhoaBieu(filename);
        } catch (IOException ex) {
            Logger.getLogger(ThoiKhoaBieu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_cbxMonHocActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThoiKhoaBieu;
    private javax.swing.JComboBox<String> cbxMonHoc;
    private javax.swing.JPanel pnThoiKhoaBieu;
    private javax.swing.JScrollPane spThoiKhoaBieu;
    private javax.swing.JTable tblThoiKhoaBieu;
    // End of variables declaration//GEN-END:variables
}
